name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install non-Rust dependencies
      run: sudo apt-get install -y libasound2-dev libusb-1.0-0-dev libudev-dev
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: X86-64 debug
        path: target/debug/dungeon-deck
      

  build-arm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross --tag v0.2.5
    - name: Build
      run: |
        cross build --target aarch64-unknown-linux-gnu --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: ARM64 debug
        path: target/aarch64-unknown-linux-gnu/debug/dungeon-deck
      
