name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Install non-Rust dependencies
      run: sudo apt-get install -y libasound2-dev libusb-1.0-0-dev
    - name: Package
      run: |
        cargo deb --verbose
        echo "DEB_NAME=$(basename $(ls target/debian/*.deb))" >> "$GITHUB_ENV"
    - uses: actions/upload-artifact@v3
      with:
        name: "{{ env.DEB_NAME }}"
        path: target/debian/*.deb

  build-release-arm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross
    - name: Package
      run: |
        cross build --release --target aarch64-unknown-linux-gnu --verbose
        cargo deb --no-build --no-strip --target aarch64-unknown-linux-gnu --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: ARM64 deb
        path: target/aarch64-unknown-linux-gnu/debian/*.deb
          
  release:
    runs-on: ubuntu-latest

    needs: [build-release, build-release-arm]

    steps:
    - name: Download debs
      uses: actions/download-artifact@v3
    - name: Release
      uses: softprops/action-gh-release@v1    
      with:
          files: ./*.deb

      
