name: Release

on:
  push:
    tags:
      - "v*.*.*"
  pull_request: #FIXME remove
    branches: [ "main" ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Install non-Rust dependencies
      run: sudo apt-get install -y libasound2-dev libusb-1.0-0-dev
    - name: Package
      run: cargo deb --verbose
    - name: Release
      uses: softprops/action-gh-release@v1    
      with:
          files: target/debian/*.deb

  release-arm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross
    - name: Package
      run: |
        cross build --release --target aarch64-unknown-linux-gnu --verbose
        cargo deb --no-build --no-strip --target aarch64-unknown-linux-gnu --verbose
    - name: Release
      uses: softprops/action-gh-release@v1    
      with:
          files: target/aarch64-unknown-linux-gnu/debian/*.deb
          
